package com.alaharranhonor.swdm.util.init;

import com.alaharranhonor.swdm.SWDM;
import net.minecraft.block.*;
import net.minecraft.block.material.Material;
import net.minecraft.item.BlockItem;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class BlockInit {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, SWDM.MOD_ID);
    public static final DeferredRegister<Block> BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, SWDM.MOD_ID);

    public static void init() {
        ITEMS.register(FMLJavaModLoadingContext.get().getModEventBus());
        BLOCKS.register(FMLJavaModLoadingContext.get().getModEventBus());
    }

    //Blocks
    public static final RegistryObject<Block> SWDM_BLACK_WOOL_STAIRS = BLOCKS.register("swdm_black_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_BLUE_WOOL_STAIRS = BLOCKS.register("swdm_blue_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_BROWN_WOOL_STAIRS = BLOCKS.register("swdm_brown_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_CYAN_WOOL_STAIRS = BLOCKS.register("swdm_cyan_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_GRAY_WOOL_STAIRS = BLOCKS.register("swdm_gray_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_GREEN_WOOL_STAIRS = BLOCKS.register("swdm_green_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_LIGHT_BLUE_WOOL_STAIRS = BLOCKS.register("swdm_light_blue_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_LIGHT_GRAY_WOOL_STAIRS = BLOCKS.register("swdm_light_gray_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_LIME_WOOL_STAIRS = BLOCKS.register("swdm_lime_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_MAGENTA_WOOL_STAIRS = BLOCKS.register("swdm_magenta_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_ORANGE_WOOL_STAIRS = BLOCKS.register("swdm_orange_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_PINK_WOOL_STAIRS = BLOCKS.register("swdm_pink_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_PURPLE_WOOL_STAIRS = BLOCKS.register("swdm_purple_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_RED_WOOL_STAIRS = BLOCKS.register("swdm_red_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_WHITE_WOOL_STAIRS = BLOCKS.register("swdm_white_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_YELLOW_WOOL_STAIRS = BLOCKS.register("swdm_yellow_wool_stairs", () -> new StairsBlock(Blocks.BLACK_WOOL.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_BLACK_WOOL_SLAB = BLOCKS.register("swdm_black_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_BLUE_WOOL_SLAB = BLOCKS.register("swdm_blue_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_BROWN_WOOL_SLAB = BLOCKS.register("swdm_brown_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_CYAN_WOOL_SLAB = BLOCKS.register("swdm_cyan_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_GRAY_WOOL_SLAB = BLOCKS.register("swdm_gray_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_GREEN_WOOL_SLAB = BLOCKS.register("swdm_green_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_LIGHT_BLUE_WOOL_SLAB = BLOCKS.register("swdm_light_blue_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_LIGHT_GRAY_WOOL_SLAB = BLOCKS.register("swdm_light_gray_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_LIME_WOOL_SLAB = BLOCKS.register("swdm_lime_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_MAGENTA_WOOL_SLAB = BLOCKS.register("swdm_magenta_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_ORANGE_WOOL_SLAB = BLOCKS.register("swdm_orange_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_PINK_WOOL_SLAB = BLOCKS.register("swdm_pink_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_PURPLE_WOOL_SLAB = BLOCKS.register("swdm_purple_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_RED_WOOL_SLAB = BLOCKS.register("swdm_red_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_WHITE_WOOL_SLAB = BLOCKS.register("swdm_white_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));
    public static final RegistryObject<Block> SWDM_YELLOW_WOOL_SLAB = BLOCKS.register("swdm_yellow_wool_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_WOOL)));

    public static final RegistryObject<Block> SWDM_ACACIA_LEAVES_STAIRS = BLOCKS.register("swdm_acacia_leaves_stairs", () -> new StairsBlock(Blocks.ACACIA_PLANKS.defaultBlockState(), Block.Properties.of(Material.LEAVES).strength(0.2F).sound(SoundType.GRASS).noOcclusion()));
    public static final RegistryObject<Block> SWDM_BIRCH_LEAVES_STAIRS = BLOCKS.register("swdm_birch_leaves_stairs", () -> new StairsBlock(Blocks.BIRCH_PLANKS.defaultBlockState(), Block.Properties.of(Material.LEAVES).strength(0.2F).sound(SoundType.GRASS).noOcclusion()));
    public static final RegistryObject<Block> SWDM_DARK_OAK_LEAVES_STAIRS = BLOCKS.register("swdm_dark_oak_leaves_stairs", () -> new StairsBlock(Blocks.DARK_OAK_PLANKS.defaultBlockState(), Block.Properties.of(Material.LEAVES).strength(0.2F).sound(SoundType.GRASS).noOcclusion()));
    public static final RegistryObject<Block> SWDM_JUNGLE_LEAVES_STAIRS = BLOCKS.register("swdm_jungle_leaves_stairs", () -> new StairsBlock(Blocks.JUNGLE_PLANKS.defaultBlockState(), Block.Properties.of(Material.LEAVES).strength(0.2F).sound(SoundType.GRASS).noOcclusion()));
    public static final RegistryObject<Block> SWDM_OAK_LEAVES_STAIRS = BLOCKS.register("swdm_oak_leaves_stairs", () -> new StairsBlock(Blocks.OAK_PLANKS.defaultBlockState(), Block.Properties.of(Material.LEAVES).strength(0.2F).sound(SoundType.GRASS).noOcclusion()));
    public static final RegistryObject<Block> SWDM_SPRUCE_LEAVES_STAIRS = BLOCKS.register("swdm_spruce_leaves_stairs", () -> new StairsBlock(Blocks.SPRUCE_PLANKS.defaultBlockState(), Block.Properties.of(Material.LEAVES).strength(0.2F).sound(SoundType.GRASS).noOcclusion()));
    public static final RegistryObject<Block> SWDM_ACACIA_LEAVES_SLAB = BLOCKS.register("swdm_acacia_leaves_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.ACACIA_LEAVES)));
    public static final RegistryObject<Block> SWDM_BIRCH_LEAVES_SLAB = BLOCKS.register("swdm_birch_leaves_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BIRCH_LEAVES)));
    public static final RegistryObject<Block> SWDM_DARK_OAK_LEAVES_SLAB = BLOCKS.register("swdm_dark_oak_leaves_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.DARK_OAK_LEAVES)));
    public static final RegistryObject<Block> SWDM_JUNGLE_LEAVES_SLAB = BLOCKS.register("swdm_jungle_leaves_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.JUNGLE_LEAVES)));
    public static final RegistryObject<Block> SWDM_OAK_LEAVES_SLAB = BLOCKS.register("swdm_oak_leaves_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> SWDM_SPRUCE_LEAVES_SLAB = BLOCKS.register("swdm_spruce_leaves_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.SPRUCE_LEAVES)));
    public static final RegistryObject<Block> SWDM_ACACIA_LEAVES_WALL = BLOCKS.register("swdm_acacia_leaves_wall", () -> new WallBlock(Block.Properties.copy(Blocks.ACACIA_LEAVES)));
    public static final RegistryObject<Block> SWDM_BIRCH_LEAVES_WALL = BLOCKS.register("swdm_birch_leaves_wall", () -> new WallBlock(Block.Properties.copy(Blocks.BIRCH_LEAVES)));
    public static final RegistryObject<Block> SWDM_DARK_OAK_LEAVES_WALL = BLOCKS.register("swdm_dark_oak_leaves_wall", () -> new WallBlock(Block.Properties.copy(Blocks.DARK_OAK_LEAVES)));
    public static final RegistryObject<Block> SWDM_JUNGLE_LEAVES_WALL = BLOCKS.register("swdm_jungle_leaves_wall", () -> new WallBlock(Block.Properties.copy(Blocks.JUNGLE_LEAVES)));
    public static final RegistryObject<Block> SWDM_OAK_LEAVES_WALL = BLOCKS.register("swdm_oak_leaves_wall", () -> new WallBlock(Block.Properties.copy(Blocks.OAK_LEAVES)));
    public static final RegistryObject<Block> SWDM_SPRUCE_LEAVES_WALL = BLOCKS.register("swdm_spruce_leaves_wall", () -> new WallBlock(Block.Properties.copy(Blocks.SPRUCE_LEAVES)));

    public static final RegistryObject<Block> SWDM_STONE_WALL = BLOCKS.register("swdm_stone_wall", () -> new WallBlock(Block.Properties.copy(Blocks.STONE)));

    public static final RegistryObject<Block> SWDM_BLACK_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_black_stained_glass_stairs", () -> new StairsBlock(Blocks.BLACK_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.BLACK_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_BLUE_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_blue_stained_glass_stairs", () -> new StairsBlock(Blocks.BLUE_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.BLUE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_BROWN_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_brown_stained_glass_stairs", () -> new StairsBlock(Blocks.BROWN_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.BROWN_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_CYAN_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_cyan_stained_glass_stairs", () -> new StairsBlock(Blocks.CYAN_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.CYAN_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_GRAY_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_gray_stained_glass_stairs", () -> new StairsBlock(Blocks.GRAY_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.GRAY_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_GREEN_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_green_stained_glass_stairs", () -> new StairsBlock(Blocks.GREEN_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.GREEN_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_LIGHT_BLUE_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_light_blue_stained_glass_stairs", () -> new StairsBlock(Blocks.LIGHT_BLUE_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.LIGHT_BLUE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_LIGHT_GRAY_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_light_gray_stained_glass_stairs", () -> new StairsBlock(Blocks.LIGHT_GRAY_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.LIGHT_GRAY_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_LIME_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_lime_stained_glass_stairs", () -> new StairsBlock(Blocks.LIME_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.LIME_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_MAGENTA_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_magenta_stained_glass_stairs", () -> new StairsBlock(Blocks.MAGENTA_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.MAGENTA_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_ORANGE_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_orange_stained_glass_stairs", () -> new StairsBlock(Blocks.ORANGE_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.ORANGE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_PINK_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_pink_stained_glass_stairs", () -> new StairsBlock(Blocks.PINK_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.PINK_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_PURPLE_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_purple_stained_glass_stairs", () -> new StairsBlock(Blocks.PURPLE_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.PURPLE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_RED_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_red_stained_glass_stairs", () -> new StairsBlock(Blocks.RED_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.RED_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_WHITE_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_white_stained_glass_stairs", () -> new StairsBlock(Blocks.WHITE_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.WHITE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_YELLOW_STAINED_GLASS_STAIRS = BLOCKS.register("swdm_yellow_stained_glass_stairs", () -> new StairsBlock(Blocks.YELLOW_STAINED_GLASS.defaultBlockState(), Block.Properties.copy(Blocks.YELLOW_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_BLACK_STAINED_GLASS_SLAB = BLOCKS.register("swdm_black_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLACK_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_BLUE_STAINED_GLASS_SLAB = BLOCKS.register("swdm_blue_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BLUE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_BROWN_STAINED_GLASS_SLAB = BLOCKS.register("swdm_brown_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.BROWN_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_CYAN_STAINED_GLASS_SLAB = BLOCKS.register("swdm_cyan_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.CYAN_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_GRAY_STAINED_GLASS_SLAB = BLOCKS.register("swdm_gray_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.GRAY_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_GREEN_STAINED_GLASS_SLAB = BLOCKS.register("swdm_green_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.GREEN_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_LIGHT_BLUE_STAINED_GLASS_SLAB = BLOCKS.register("swdm_light_blue_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.LIGHT_BLUE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_LIGHT_GRAY_STAINED_GLASS_SLAB = BLOCKS.register("swdm_light_gray_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.LIGHT_GRAY_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_LIME_STAINED_GLASS_SLAB = BLOCKS.register("swdm_lime_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.LIME_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_MAGENTA_STAINED_GLASS_SLAB = BLOCKS.register("swdm_magenta_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.MAGENTA_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_ORANGE_STAINED_GLASS_SLAB = BLOCKS.register("swdm_orange_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.ORANGE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_PINK_STAINED_GLASS_SLAB = BLOCKS.register("swdm_pink_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.PINK_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_PURPLE_STAINED_GLASS_SLAB = BLOCKS.register("swdm_purple_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.PURPLE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_RED_STAINED_GLASS_SLAB = BLOCKS.register("swdm_red_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.RED_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_WHITE_STAINED_GLASS_SLAB = BLOCKS.register("swdm_white_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.WHITE_STAINED_GLASS)));
    public static final RegistryObject<Block> SWDM_YELLOW_STAINED_GLASS_SLAB = BLOCKS.register("swdm_yellow_stained_glass_slab", () -> new SlabBlock(Block.Properties.copy(Blocks.YELLOW_STAINED_GLASS)));

    //Items

    //Block Items
    public static final RegistryObject<Item> SWDM_BLACK_WOOL_STAIRS_ITEM = ITEMS.register("swdm_black_wool_stairs", () -> new BlockItem(SWDM_BLACK_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BLUE_WOOL_STAIRS_ITEM = ITEMS.register("swdm_blue_wool_stairs", () -> new BlockItem(SWDM_BLUE_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BROWN_WOOL_STAIRS_ITEM = ITEMS.register("swdm_brown_wool_stairs", () -> new BlockItem(SWDM_BROWN_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_CYAN_WOOL_STAIRS_ITEM = ITEMS.register("swdm_cyan_wool_stairs", () -> new BlockItem(SWDM_CYAN_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_GRAY_WOOL_STAIRS_ITEM = ITEMS.register("swdm_gray_wool_stairs", () -> new BlockItem(SWDM_GRAY_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_GREEN_WOOL_STAIRS_ITEM = ITEMS.register("swdm_green_wool_stairs", () -> new BlockItem(SWDM_GREEN_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIGHT_BLUE_WOOL_STAIRS_ITEM = ITEMS.register("swdm_light_blue_wool_stairs", () -> new BlockItem(SWDM_LIGHT_BLUE_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIGHT_GRAY_WOOL_STAIRS_ITEM = ITEMS.register("swdm_light_gray_wool_stairs", () -> new BlockItem(SWDM_LIGHT_GRAY_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIME_WOOL_STAIRS_ITEM = ITEMS.register("swdm_lime_wool_stairs", () -> new BlockItem(SWDM_LIME_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_MAGENTA_WOOL_STAIRS_ITEM = ITEMS.register("swdm_magenta_wool_stairs", () -> new BlockItem(SWDM_MAGENTA_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_ORANGE_WOOL_STAIRS_ITEM = ITEMS.register("swdm_orange_wool_stairs", () -> new BlockItem(SWDM_ORANGE_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_PINK_WOOL_STAIRS_ITEM = ITEMS.register("swdm_pink_wool_stairs", () -> new BlockItem(SWDM_PINK_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_PURPLE_WOOL_STAIRS_ITEM = ITEMS.register("swdm_purple_wool_stairs", () -> new BlockItem(SWDM_PURPLE_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_RED_WOOL_STAIRS_ITEM = ITEMS.register("swdm_red_wool_stairs", () -> new BlockItem(SWDM_RED_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_WHITE_WOOL_STAIRS_ITEM = ITEMS.register("swdm_white_wool_stairs", () -> new BlockItem(SWDM_WHITE_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_YELLOW_WOOL_STAIRS_ITEM = ITEMS.register("swdm_yellow_wool_stairs", () -> new BlockItem(SWDM_YELLOW_WOOL_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BLACK_WOOL_SLAB_ITEM = ITEMS.register("swdm_black_wool_slab", () -> new BlockItem(SWDM_BLACK_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BLUE_WOOL_SLAB_ITEM = ITEMS.register("swdm_blue_wool_slab", () -> new BlockItem(SWDM_BLUE_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BROWN_WOOL_SLAB_ITEM = ITEMS.register("swdm_brown_wool_slab", () -> new BlockItem(SWDM_BROWN_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_CYAN_WOOL_SLAB_ITEM = ITEMS.register("swdm_cyan_wool_slab", () -> new BlockItem(SWDM_CYAN_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_GRAY_WOOL_SLAB_ITEM = ITEMS.register("swdm_gray_wool_slab", () -> new BlockItem(SWDM_GRAY_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_GREEN_WOOL_SLAB_ITEM = ITEMS.register("swdm_green_wool_slab", () -> new BlockItem(SWDM_GREEN_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIGHT_BLUE_WOOL_SLAB_ITEM = ITEMS.register("swdm_light_blue_wool_slab", () -> new BlockItem(SWDM_LIGHT_BLUE_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIGHT_GRAY_WOOL_SLAB_ITEM = ITEMS.register("swdm_light_gray_wool_slab", () -> new BlockItem(SWDM_LIGHT_GRAY_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIME_WOOL_SLAB_ITEM = ITEMS.register("swdm_lime_wool_slab", () -> new BlockItem(SWDM_LIME_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_MAGENTA_WOOL_SLAB_ITEM = ITEMS.register("swdm_magenta_wool_slab", () -> new BlockItem(SWDM_MAGENTA_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_ORANGE_WOOL_SLAB_ITEM = ITEMS.register("swdm_orange_wool_slab", () -> new BlockItem(SWDM_ORANGE_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_PINK_WOOL_SLAB_ITEM = ITEMS.register("swdm_pink_wool_slab", () -> new BlockItem(SWDM_PINK_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_PURPLE_WOOL_SLAB_ITEM = ITEMS.register("swdm_purple_wool_slab", () -> new BlockItem(SWDM_PURPLE_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_RED_WOOL_SLAB_ITEM = ITEMS.register("swdm_red_wool_slab", () -> new BlockItem(SWDM_RED_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_WHITE_WOOL_SLAB_ITEM = ITEMS.register("swdm_white_wool_slab", () -> new BlockItem(SWDM_WHITE_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_YELLOW_WOOL_SLAB_ITEM = ITEMS.register("swdm_yellow_wool_slab", () -> new BlockItem(SWDM_YELLOW_WOOL_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_ACACIA_LEAVES_STAIRS_ITEM = ITEMS.register("swdm_acacia_leaves_stairs", () -> new BlockItem(SWDM_ACACIA_LEAVES_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BIRCH_LEAVES_STAIRS_ITEM = ITEMS.register("swdm_birch_leaves_stairs", () -> new BlockItem(SWDM_BIRCH_LEAVES_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_DARK_OAK_LEAVES_STAIRS_ITEM = ITEMS.register("swdm_dark_oak_leaves_stairs", () -> new BlockItem(SWDM_DARK_OAK_LEAVES_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_JUNGLE_LEAVES_STAIRS_ITEM = ITEMS.register("swdm_jungle_leaves_stairs", () -> new BlockItem(SWDM_JUNGLE_LEAVES_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_OAK_LEAVES_STAIRS_ITEM = ITEMS.register("swdm_oak_leaves_stairs", () -> new BlockItem(SWDM_OAK_LEAVES_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_SPRUCE_LEAVES_STAIRS_ITEM = ITEMS.register("swdm_spruce_leaves_stairs", () -> new BlockItem(SWDM_SPRUCE_LEAVES_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_ACACIA_LEAVES_SLAB_ITEM = ITEMS.register("swdm_acacia_leaves_slab", () -> new BlockItem(SWDM_ACACIA_LEAVES_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BIRCH_LEAVES_SLAB_ITEM = ITEMS.register("swdm_birch_leaves_slab", () -> new BlockItem(SWDM_BIRCH_LEAVES_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_DARK_OAK_LEAVES_SLAB_ITEM = ITEMS.register("swdm_dark_oak_leaves_slab", () -> new BlockItem(SWDM_DARK_OAK_LEAVES_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_JUNGLE_LEAVES_SLAB_ITEM = ITEMS.register("swdm_jungle_leaves_slab", () -> new BlockItem(SWDM_JUNGLE_LEAVES_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_OAK_LEAVES_SLAB_ITEM = ITEMS.register("swdm_oak_leaves_slab", () -> new BlockItem(SWDM_OAK_LEAVES_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_SPRUCE_LEAVES_SLAB_ITEM = ITEMS.register("swdm_spruce_leaves_slab", () -> new BlockItem(SWDM_SPRUCE_LEAVES_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_ACACIA_LEAVES_WALL_ITEM = ITEMS.register("swdm_acacia_leaves_wall", () -> new BlockItem(SWDM_ACACIA_LEAVES_WALL.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BIRCH_LEAVES_WALL_ITEM = ITEMS.register("swdm_birch_leaves_wall", () -> new BlockItem(SWDM_BIRCH_LEAVES_WALL.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_DARK_OAK_LEAVES_WALL_ITEM = ITEMS.register("swdm_dark_oak_leaves_wall", () -> new BlockItem(SWDM_DARK_OAK_LEAVES_WALL.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_JUNGLE_LEAVES_WALL_ITEM = ITEMS.register("swdm_jungle_leaves_wall", () -> new BlockItem(SWDM_JUNGLE_LEAVES_WALL.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_OAK_LEAVES_WALL_ITEM = ITEMS.register("swdm_oak_leaves_wall", () -> new BlockItem(SWDM_OAK_LEAVES_WALL.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_SPRUCE_LEAVES_WALL_ITEM = ITEMS.register("swdm_spruce_leaves_wall", () -> new BlockItem(SWDM_SPRUCE_LEAVES_WALL.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_STONE_WALL_ITEM = ITEMS.register("swdm_stone_wall", () -> new BlockItem(SWDM_STONE_WALL.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BLACK_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_black_stained_glass_stairs", () -> new BlockItem(SWDM_BLACK_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BLUE_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_blue_stained_glass_stairs", () -> new BlockItem(SWDM_BLUE_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BROWN_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_brown_stained_glass_stairs", () -> new BlockItem(SWDM_BROWN_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_CYAN_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_cyan_stained_glass_stairs", () -> new BlockItem(SWDM_CYAN_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_GRAY_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_gray_stained_glass_stairs", () -> new BlockItem(SWDM_GRAY_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_GREEN_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_green_stained_glass_stairs", () -> new BlockItem(SWDM_GREEN_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIGHT_BLUE_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_light_blue_stained_glass_stairs", () -> new BlockItem(SWDM_LIGHT_BLUE_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIGHT_GRAY_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_light_gray_stained_glass_stairs", () -> new BlockItem(SWDM_LIGHT_GRAY_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIME_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_lime_stained_glass_stairs", () -> new BlockItem(SWDM_LIME_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_MAGENTA_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_magenta_stained_glass_stairs", () -> new BlockItem(SWDM_MAGENTA_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_ORANGE_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_orange_stained_glass_stairs", () -> new BlockItem(SWDM_ORANGE_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_PINK_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_pink_stained_glass_stairs", () -> new BlockItem(SWDM_PINK_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_PURPLE_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_purple_stained_glass_stairs", () -> new BlockItem(SWDM_PURPLE_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_RED_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_red_stained_glass_stairs", () -> new BlockItem(SWDM_RED_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_WHITE_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_white_stained_glass_stairs", () -> new BlockItem(SWDM_WHITE_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_YELLOW_STAINED_GLASS_STAIRS_ITEM = ITEMS.register("swdm_yellow_stained_glass_stairs", () -> new BlockItem(SWDM_YELLOW_STAINED_GLASS_STAIRS.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BLACK_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_black_stained_glass_slab", () -> new BlockItem(SWDM_BLACK_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BLUE_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_blue_stained_glass_slab", () -> new BlockItem(SWDM_BLUE_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_BROWN_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_brown_stained_glass_slab", () -> new BlockItem(SWDM_BROWN_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_CYAN_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_cyan_stained_glass_slab", () -> new BlockItem(SWDM_CYAN_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_GRAY_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_gray_stained_glass_slab", () -> new BlockItem(SWDM_GRAY_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_GREEN_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_green_stained_glass_slab", () -> new BlockItem(SWDM_GREEN_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIGHT_BLUE_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_light_blue_stained_glass_slab", () -> new BlockItem(SWDM_LIGHT_BLUE_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIGHT_GRAY_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_light_gray_stained_glass_slab", () -> new BlockItem(SWDM_LIGHT_GRAY_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_LIME_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_lime_stained_glass_slab", () -> new BlockItem(SWDM_LIME_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_MAGENTA_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_magenta_stained_glass_slab", () -> new BlockItem(SWDM_MAGENTA_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_ORANGE_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_orange_stained_glass_slab", () -> new BlockItem(SWDM_ORANGE_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_PINK_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_pink_stained_glass_slab", () -> new BlockItem(SWDM_PINK_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_PURPLE_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_purple_stained_glass_slab", () -> new BlockItem(SWDM_PURPLE_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_RED_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_red_stained_glass_slab", () -> new BlockItem(SWDM_RED_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_WHITE_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_white_stained_glass_slab", () -> new BlockItem(SWDM_WHITE_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));
    public static final RegistryObject<Item> SWDM_YELLOW_STAINED_GLASS_SLAB_ITEM = ITEMS.register("swdm_yellow_stained_glass_slab", () -> new BlockItem(SWDM_YELLOW_STAINED_GLASS_SLAB.get(), new Item.Properties().tab(SWDM.SWDMTAB)));

}
