name: 'Release'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Release'
    steps:
      - uses: actions/checkout@v2
        name: "Checkout Repository"
      - name: "Setup JDK 8"
        uses: actions/setup-java@v2
        with: { distribution: "adopt", java-version: "8" }
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle
        id: build
        run: chmod +x gradlew && ./gradlew build curseforge ${{ format('-Pcurseforge_key={0}', secrets.CURSEFORGE_API_KEY) }}