name: 'Release'

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Release'
    steps:
      - uses: actions/checkout@v3
        name: "Checkout Repository"
      - name: "Setup JDK 17"
        uses: actions/setup-java@v3
        with: { distribution: "adopt", java-version: "17" }
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3
      - name: Build modules
        id: build
        run: |
          gradle :build --no-daemon
      - name: Publish Mods
        uses: Kir-Antipov/mc-publish@v3.2
        id: release-mods
        with:
          loaders: |
            forge
          modrinth-id: aYxsAaJ3
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: 568104
          curseforge-token: ${{ secrets.CURSEFORGE_API_KEY }}
          changelog-file: changelog.md
      - name: Send webhook
        run: gradle :sendWebhook ${{ format('-Pcurseforge_file_url={0} -Pmodrinth_file-url={1} -Pdiscord_webhook_url={2}', steps.release-mods.outputs.curseforge-url, steps.release-mods.outputs.modrinth-url, secrets.WEBHOOK_URL) }}